---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  strategy: {}
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: schen13912/vmc-frontend:v2
        imagePullPolicy: Always
        env:
        - name: LATTICEURL
          value: "http://{LATTICE_URL}"
        - name: LATTICEURL2
          value: "http://{LATTICE_URL_2}"
        ports:
          - containerPort: 8080
        resources: {}
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  selector:
    app: front-end
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
